import fitz
import pytest
from fastapi import HTTPException
from app.utils.pdf import extract_text_from_pdf, generate_pdf


def test_extract_text_from_pdf_success(valid_pdf):
    """Test successful text extraction from a valid PDF."""
    text = extract_text_from_pdf(valid_pdf)
    assert "John Doe" in text
    assert "john@example.com" in text
    assert "FastAPI" in text


def test_extract_text_from_pdf_empty(empty_pdf):
    """Test that an empty PDF raises HTTPException 400."""
    with pytest.raises(HTTPException) as exc_info:
        extract_text_from_pdf(empty_pdf)
    assert exc_info.value.status_code == 400
    assert "No readable text found" in exc_info.value.detail


def test_extract_text_from_pdf_corrupted(corrupted_pdf):
    """Test that a corrupted PDF raises HTTPException 400."""
    with pytest.raises(HTTPException) as exc_info:
        extract_text_from_pdf(corrupted_pdf)
    assert exc_info.value.status_code == 400
    assert "Failed to read the uploaded PDF" in exc_info.value.detail


def test_extract_text_from_pdf_image_only(image_only_pdf):
    """Test that an image-only PDF with no readable text raises HTTPException 400."""
    with pytest.raises(HTTPException) as exc_info:
        extract_text_from_pdf(image_only_pdf)
    assert exc_info.value.status_code == 400
    assert "No readable text found" in exc_info.value.detail


def test_extract_text_from_pdf_max_pages():
    """Test that a PDF exceeding the maximum allowed page count raises HTTPException 400."""
    # Create a mock PDF with 11 pages (MAX_PDF_PAGES = 10)
    doc = fitz.open()
    for _ in range(11):
        doc.new_page()
    oversized_pdf = doc.write()
    doc.close()

    with pytest.raises(HTTPException) as exc_info:
        extract_text_from_pdf(oversized_pdf)
    assert exc_info.value.status_code == 400
    assert "Resume exceeds the maximum limit" in exc_info.value.detail


def test_generate_pdf_success():
    """Test that generate_pdf creates valid PDF bytes containing the input text."""
    test_text = "Hello, this is a test PDF generator verification."
    pdf_bytes = generate_pdf(test_text)

    # Verify that the generated bytes form a valid PDF that can be parsed by fitz
    assert isinstance(pdf_bytes, bytes)
    assert len(pdf_bytes) > 0

    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    assert doc.page_count == 1
    page_text = doc[0].get_text()
    doc.close()

    # The text might be formatted/wrapped, check substring existence
    assert "Hello, this is a test" in page_text


def test_extract_text_from_live_pdf(live_pdf_bytes):
    """Test text extraction on a live user-provided PDF file if --pdf-path is specified."""
    if live_pdf_bytes is None:
        pytest.skip("No live PDF file provided via --pdf-path option.")

    text = extract_text_from_pdf(live_pdf_bytes)
    assert isinstance(text, str)
    assert len(text) > 0
    print(f"\n[LIVE PDF] Successfully extracted {len(text)} characters.")
